import { createGraph } from '../models/graph.js';

export const MAP_WIDTH = 1024;
export const MAP_HEIGHT = 512;

export function createCampusGraph() {
  const g = createGraph();

  // TEMPLATE VERTICES
  g.addVertex({ id: 'EmergencyGenerator',   name: 'Emergency Generator Building',         x: 135, y: 318, isTerminal: false });
  g.addVertex({ id: 'AlbrookHydraulics',    name: 'Albrook Hydraulics Lab',               x: 150, y: 202, isTerminal: false });
  g.addVertex({ id: 'SloanHall',            name: 'Sloan Hall',                           x: 247, y: 226, isTerminal: false });
  g.addVertex({ id: 'EME',                  name: 'Electrical / Mechanical Engineering',  x: 214, y: 257, isTerminal: false });
  g.addVertex({ id: 'EngineeringResearch',  name: 'Engineering Research Lab',             x: 194, y: 315, isTerminal: false });
  g.addVertex({ id: 'IdaLouAnderson',       name: 'Ida Lou Anderson',                     x: 206, y: 131, isTerminal: false });
  g.addVertex({ id: 'ElminaWhiteHonors',    name: 'Elmina White Honors Hall',             x: 290, y: 153, isTerminal: false });
  g.addVertex({ id: 'McCroskeyHall',        name: 'McCroskey Hall',                       x: 354, y: 128, isTerminal: false });
  g.addVertex({ id: 'DuncanDunn',           name: 'Duncan Dunn Hall',                     x: 323, y: 71,  isTerminal: false });
  g.addVertex({ id: 'WilmerDavis',          name: 'Wilmer Davis Hall',                    x: 367, y: 75,  isTerminal: false });
  g.addVertex({ id: 'Stevens',              name: 'Stevens Hall',                         x: 390, y: 151, isTerminal: false });
  g.addVertex({ id: 'Avery',                name: 'Avery Hall',                           x: 419, y: 145, isTerminal: false });
  g.addVertex({ id: 'Bryan',                name: 'Bryan Hall',                           x: 433, y: 183, isTerminal: false });
  g.addVertex({ id: 'Thompson',             name: 'Thompson Hall',                        x: 352, y: 193, isTerminal: false });
  g.addVertex({ id: 'Goertzen',             name: 'Goertzen Hall',                        x: 343, y: 232, isTerminal: false });
  g.addVertex({ id: 'Murrow',               name: 'Murrow Hall',                          x: 403, y: 240, isTerminal: false });
  g.addVertex({ id: 'Morril',               name: 'Morril Hall',                          x: 347, y: 269, isTerminal: false });
  g.addVertex({ id: 'VanDoren',             name: 'Van Doren Hall',                       x: 470, y: 143, isTerminal: false });
  g.addVertex({ id: 'KimbroughMusic',       name: 'Kimbrough Music',                      x: 451, y: 110, isTerminal: false });
  g.addVertex({ id: 'ChinookStudentCenter', name: 'Chinook Student Center',               x: 436, y: 62,  isTerminal: false });
  g.addVertex({ id: 'SmithGym',             name: 'Smith Gymnasium',                      x: 492, y: 62,  isTerminal: false });
  g.addVertex({ id: 'BohlerGym',            name: 'Bohler Gymnasium',                     x: 587, y: 65,  isTerminal: false });
  g.addVertex({ id: 'BohlerGymAdd',         name: 'Bohler Gymnasium Addition',            x: 587, y: 30,  isTerminal: false });
  g.addVertex({ id: 'FieldHouse',           name: 'Hollingbery Field House',              x: 637, y: 60,  isTerminal: false });
  g.addVertex({ id: 'MooberryTrack',        name: 'Mooberry Track',                       x: 684, y: 24,  isTerminal: false });
  g.addVertex({ id: 'MartinStadium',        name: 'Martin Stadium',                       x: 674, y: 143, isTerminal: false });
  g.addVertex({ id: 'RogersField',          name: 'Rogers Field',                         x: 565, y: 138, isTerminal: false });
  g.addVertex({ id: 'IT',                   name: 'Information Technology',               x: 717, y: 214, isTerminal: false });
  g.addVertex({ id: 'CUB',                  name: 'Compton Union Building',               x: 564, y: 210, isTerminal: false });
  g.addVertex({ id: 'HallandLib',           name: 'Halland Library',                      x: 487, y: 195, isTerminal: false });
  g.addVertex({ id: 'College',              name: 'College Hall',                         x: 478, y: 259, isTerminal: false });
  g.addVertex({ id: 'Todd',                 name: 'Todd Hall',                            x: 504, y: 311, isTerminal: false });
  g.addVertex({ id: 'JohnsonTower',         name: 'Johnson Tower',                        x: 560, y: 318, isTerminal: false });
  g.addVertex({ id: 'Schnitzer',            name: 'Schnitzer Museum  of Art',             x: 624, y: 265, isTerminal: false });
  g.addVertex({ id: 'SmithCenter',          name: 'Smith Center',                         x: 614, y: 313, isTerminal: false });
  g.addVertex({ id: 'FineArtsCenter',       name: 'Fine Arts Center',                     x: 685, y: 287, isTerminal: false });
  g.addVertex({ id: 'WilsonShort',          name: 'Wilson Short Hall',                    x: 571, y: 270, isTerminal: false });
  g.addVertex({ id: 'Fulmer',               name: 'Fulmer Hall Lab',                      x: 475, y: 351, isTerminal: false });
  g.addVertex({ id: 'FulmerSynthesis',      name: 'Fulmer Hall Synthesis',                x: 535, y: 359, isTerminal: false });
  g.addVertex({ id: 'WebsterPS',            name: 'Webster Physical Science',             x: 538, y: 407, isTerminal: false });
  g.addVertex({ id: 'Stimson',              name: 'Stimson Hall',                         x: 465, y: 394, isTerminal: false });
  g.addVertex({ id: 'Cleveland',            name: 'Cleveland Hall',                       x: 379, y: 409, isTerminal: false });
  g.addVertex({ id: 'Spark',                name: 'The Spark Academic',                   x: 404, y: 456, isTerminal: false });
  g.addVertex({ id: 'Carpenter',            name: 'Carpenter Hall',                       x: 282, y: 302, isTerminal: false });
  g.addVertex({ id: 'Dana',                 name: 'Dana Hall',                            x: 240, y: 300, isTerminal: false });
  g.addVertex({ id: 'ChilledWater',         name: 'Chilled Water Plant',                  x: 194, y: 402, isTerminal: false });
  g.addVertex({ id: 'EngineeringLab',       name: 'Engineering Lab',                      x: 166, y: 323, isTerminal: false });
  g.addVertex({ id: 'ThermalFluids',        name: 'Thermal Fluids Research',              x: 162, y: 270, isTerminal: false });
  g.addVertex({ id: 'Daggy',                name: 'Daggy Hall',                           x: 309, y: 322, isTerminal: false });
  g.addVertex({ id: 'Eastlick',             name: 'Eastlick Hall',                        x: 387, y: 307, isTerminal: false });
  g.addVertex({ id: 'EducAdd',              name: 'Education Addition',                   x: 359, y: 442, isTerminal: false });
  g.addVertex({ id: 'OwenSciEng',           name: 'Owen Science & Engineering Lab',       x: 421, y: 405, isTerminal: false });
  g.addVertex({ id: 'Heald',                name: 'Heald Hall',                           x: 385, y: 342, isTerminal: false });
  g.addVertex({ id: 'Abelson',              name: 'Abelson Hall',                         x: 423, y: 333, isTerminal: false });
  g.addVertex({ id: 'MLA',                  name: 'Math Learning Annex',                  x: 343, y: 333, isTerminal: false });
  g.addVertex({ id: 'Jackson',              name: 'Jackson Hall',                         x: 379, y: 224, isTerminal: false });
  g.addVertex({ id: 'VeterinaryTeaching',   name: 'Veterinary Teaching Hospital',         x: 765, y: 473, isTerminal: false });
  g.addVertex({ id: 'Bustad',               name: 'Bustad Hall',                          x: 729, y: 398, isTerminal: false });
  g.addVertex({ id: 'McCoy',                name: 'McCoy Hall',                           x: 678, y: 437, isTerminal: false });
  g.addVertex({ id: 'Wegner',               name: 'Wegner Hall',                          x: 629, y: 451, isTerminal: false });
  g.addVertex({ id: 'Troy',                 name: 'Troy Hall',                            x: 563, y: 357, isTerminal: false });
  g.addVertex({ id: 'TerrellLib',           name: 'Terrell Library',                      x: 523, y: 196, isTerminal: false });
  g.addVertex({ id: 'GrimesWay',            name: 'Grimes Way Playfield',                 x: 897, y: 276, isTerminal: false });
  g.addVertex({ id: 'FrenchAdmin',          name: 'French Administration',                x: 784, y: 262, isTerminal: false });
  g.addVertex({ id: 'LightySS',             name: 'Lighty Student Services',              x: 822, y: 263, isTerminal: false });
  g.addVertex({ id: 'Johnson',              name: 'Johnson Hall',                         x: 817, y: 184, isTerminal: false });
  g.addVertex({ id: 'VogelPlant',           name: 'Vogel Plant Biosciences',              x: 777, y: 164, isTerminal: false });
  g.addVertex({ id: 'VeterinaryBiomedical', name: 'Veterinary And Biomedical Research',   x: 851, y: 54,  isTerminal: false });
  g.addVertex({ id: 'Biotechnology',        name: 'Biotechnology / Life Sciences',        x: 804, y: 86,  isTerminal: false });
  g.addVertex({ id: 'PlantSciences',        name: 'Plant Sciences',                       x: 855, y: 108, isTerminal: false });
  g.addVertex({ id: 'Clark',                name: 'Clark Hall',                           x: 910, y: 129, isTerminal: false });
  g.addVertex({ id: 'Hulbert',              name: 'Hulbert Hall',                         x: 947, y: 169, isTerminal: false });
  g.addVertex({ id: 'FoodScience',          name: 'Food Science / Human Nutrition',       x: 918, y: 86,  isTerminal: false });
  g.addVertex({ id: 'FoodQuality',          name: 'Food Quality',                         x: 969, y: 83,  isTerminal: false });
  g.addVertex({ id: 'PaccarEnvTech',        name: 'Paccar Environmental Technology',      x: 960, y: 335, isTerminal: false });
  g.addVertex({ id: 'USDAAgri',             name: 'USDA Agriculture Research Center',     x: 962, y: 292, isTerminal: false });
  g.addVertex({ id: 'PhysicalEdu',          name: 'Physical Education',                   x: 533, y: 63,  isTerminal: false });


  // TEMPLATE EDGES
  g.addEdge({ id: 'TEMPLATE_E1',    u: 'IdaLouAnderson',        v: 'DuncanDunn',            weight: 131 });
  g.addEdge({ id: 'TEMPLATE_E2',    u: 'ElminaWhiteHonors',     v: 'DuncanDunn',            weight: 88 });
  g.addEdge({ id: 'TEMPLATE_E3',    u: 'ElminaWhiteHonors',     v: 'IdaLouAnderson',        weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E4',    u: 'ElminaWhiteHonors',     v: 'McCroskeyHall',         weight: 69 });
  g.addEdge({ id: 'TEMPLATE_E5',    u: 'ElminaWhiteHonors',     v: 'WilmerDavis',           weight: 110 });
  g.addEdge({ id: 'TEMPLATE_E6',    u: 'ElminaWhiteHonors',     v: 'Thompson',              weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E7',    u: 'ElminaWhiteHonors',     v: 'Goertzen',              weight: 95 });
  g.addEdge({ id: 'TEMPLATE_E8',    u: 'Morril',                v: 'ElminaWhiteHonors',     weight: 129 });
  g.addEdge({ id: 'TEMPLATE_E9',    u: 'ElminaWhiteHonors',     v: 'SloanHall',             weight: 85 });
  g.addEdge({ id: 'TEMPLATE_E10',   u: 'Carpenter',             v: 'ElminaWhiteHonors',     weight: 149 });
  g.addEdge({ id: 'TEMPLATE_E11',   u: 'Daggy',                 v: 'ElminaWhiteHonors',     weight: 170 });
  g.addEdge({ id: 'TEMPLATE_E12',   u: 'ElminaWhiteHonors',     v: 'Stevens',               weight: 100 });
  g.addEdge({ id: 'TEMPLATE_E13',   u: 'ElminaWhiteHonors',     v: 'AlbrookHydraulics',     weight: 148 });
  g.addEdge({ id: 'TEMPLATE_E14',   u: 'McCroskeyHall',         v: 'WilmerDavis',           weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E15',   u: 'McCroskeyHall',         v: 'DuncanDunn',            weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E16',   u: 'McCroskeyHall',         v: 'Stevens',               weight: 43 });
  g.addEdge({ id: 'TEMPLATE_E17',   u: 'McCroskeyHall',         v: 'Thompson',              weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E18',   u: 'Stevens',               v: 'Avery',                 weight: 30 });
  g.addEdge({ id: 'TEMPLATE_E19',   u: 'Stevens',               v: 'Bryan',                 weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E20',   u: 'Stevens',               v: 'Thompson',              weight: 57 });
  g.addEdge({ id: 'TEMPLATE_E21',   u: 'Stevens',               v: 'Jackson',               weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E22',   u: 'Stevens',               v: 'Murrow',                weight: 90 });
  g.addEdge({ id: 'TEMPLATE_E23',   u: 'WilmerDavis',           v: 'DuncanDunn',            weight: 44 });
  g.addEdge({ id: 'TEMPLATE_E24',   u: 'WilmerDavis',           v: 'ChinookStudentCenter',  weight: 70 });
  g.addEdge({ id: 'TEMPLATE_E25',   u: 'WilmerDavis',           v: 'KimbroughMusic',        weight: 91 });
  g.addEdge({ id: 'TEMPLATE_E26',   u: 'IdaLouAnderson',        v: 'SloanHall',             weight: 103 });
  g.addEdge({ id: 'TEMPLATE_E27',   u: 'IdaLouAnderson',        v: 'AlbrookHydraulics',     weight: 90 });
  g.addEdge({ id: 'TEMPLATE_E28',   u: 'IdaLouAnderson',        v: 'ThermalFluids',         weight: 146 });
  g.addEdge({ id: 'TEMPLATE_E29',   u: 'AlbrookHydraulics',     v: 'ThermalFluids',         weight: 69 });
  g.addEdge({ id: 'TEMPLATE_E30',   u: 'AlbrookHydraulics',     v: 'EME',                   weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E31',   u: 'EME',                   v: 'SloanHall',             weight: 45 });
  g.addEdge({ id: 'TEMPLATE_E32',   u: 'EME',                   v: 'Dana',                  weight: 50 });
  g.addEdge({ id: 'TEMPLATE_E33',   u: 'Dana',                  v: 'SloanHall',             weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E34',   u: 'EME',                   v: 'EngineeringResearch',   weight: 61 });
  g.addEdge({ id: 'TEMPLATE_E35',   u: 'EngineeringResearch',   v: 'Dana',                  weight: 48 });
  g.addEdge({ id: 'TEMPLATE_E36',   u: 'EME',                   v: 'ThermalFluids',         weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E37',   u: 'ThermalFluids',         v: 'EmergencyGenerator',    weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E38',   u: 'ThermalFluids',         v: 'EngineeringLab',        weight: 53 });
  g.addEdge({ id: 'TEMPLATE_E39',   u: 'EngineeringLab',        v: 'EmergencyGenerator',    weight: 31 });
  g.addEdge({ id: 'TEMPLATE_E40',   u: 'EngineeringLab',        v: 'EngineeringResearch',   weight: 29 });
  g.addEdge({ id: 'TEMPLATE_E41',   u: 'EngineeringResearch',   v: 'ThermalFluids',         weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E42',   u: 'Dana',                  v: 'Carpenter',             weight: 42 });
  g.addEdge({ id: 'TEMPLATE_E43',   u: 'Carpenter',             v: 'Daggy',                 weight: 34 });
  g.addEdge({ id: 'TEMPLATE_E44',   u: 'Daggy',                 v: 'MLA',                   weight: 36 });
  g.addEdge({ id: 'TEMPLATE_E45',   u: 'MLA',                   v: 'Heald',                 weight: 43 });
  g.addEdge({ id: 'TEMPLATE_E46',   u: 'Heald',                 v: 'Abelson',               weight: 39 });
  g.addEdge({ id: 'TEMPLATE_E47',   u: 'EngineeringLab',        v: 'ChilledWater',          weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E48',   u: 'ChilledWater',          v: 'EducAdd',               weight: 170 });
  g.addEdge({ id: 'TEMPLATE_E49',   u: 'EducAdd',               v: 'Cleveland',             weight: 39 });
  g.addEdge({ id: 'TEMPLATE_E50',   u: 'Cleveland',             v: 'Spark',                 weight: 53 });
  g.addEdge({ id: 'TEMPLATE_E51',   u: 'Spark',                 v: 'OwenSciEng',            weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E52',   u: 'EducAdd',               v: 'Spark',                 weight: 47 });
  g.addEdge({ id: 'TEMPLATE_E53',   u: 'Spark',                 v: 'Stimson',               weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E54',   u: 'Stimson',               v: 'WebsterPS',             weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E55',   u: 'WebsterPS',             v: 'Wegner',                weight: 101 });
  g.addEdge({ id: 'TEMPLATE_E56',   u: 'Wegner',                v: 'McCoy',                 weight: 51 });
  g.addEdge({ id: 'TEMPLATE_E57',   u: 'McCoy',                 v: 'Bustad',                weight: 64 });
  g.addEdge({ id: 'TEMPLATE_E58',   u: 'Bustad',                v: 'VeterinaryTeaching',    weight: 83 });
  g.addEdge({ id: 'TEMPLATE_E59',   u: 'VeterinaryTeaching',    v: 'PaccarEnvTech',         weight: 239 });
  g.addEdge({ id: 'TEMPLATE_E60',   u: 'PaccarEnvTech',         v: 'USDAAgri',              weight: 43 });
  g.addEdge({ id: 'TEMPLATE_E61',   u: 'USDAAgri',              v: 'Hulbert',               weight: 124 });
  g.addEdge({ id: 'TEMPLATE_E63',   u: 'FoodQuality',           v: 'FoodScience',           weight: 51 });
  g.addEdge({ id: 'TEMPLATE_E64',   u: 'FoodScience',           v: 'VeterinaryBiomedical',  weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E65',   u: 'VeterinaryBiomedical',  v: 'Biotechnology',         weight: 57 });
  g.addEdge({ id: 'TEMPLATE_E66',   u: 'Biotechnology',         v: 'MooberryTrack',         weight: 135 });
  g.addEdge({ id: 'TEMPLATE_E67',   u: 'MooberryTrack',         v: 'FieldHouse',            weight: 59 });
  g.addEdge({ id: 'TEMPLATE_E68',   u: 'FieldHouse',            v: 'BohlerGym',             weight: 50 });
  g.addEdge({ id: 'TEMPLATE_E69',   u: 'BohlerGym',             v: 'BohlerGymAdd',          weight: 35 });
  g.addEdge({ id: 'TEMPLATE_E70',   u: 'BohlerGymAdd',          v: 'PhysicalEdu',           weight: 63 });
  g.addEdge({ id: 'TEMPLATE_E71',   u: 'PhysicalEdu',           v: 'SmithGym',              weight: 41 });
  g.addEdge({ id: 'TEMPLATE_E72',   u: 'SmithGym',              v: 'ChinookStudentCenter',  weight: 56 });
  g.addEdge({ id: 'TEMPLATE_E73',   u: 'Jackson',               v: 'Goertzen',              weight: 37 });
  g.addEdge({ id: 'TEMPLATE_E74',   u: 'Thompson',              v: 'Goertzen',              weight: 40 });
  g.addEdge({ id: 'TEMPLATE_E75',   u: 'Jackson',               v: 'Thompson',              weight: 41 });
  g.addEdge({ id: 'TEMPLATE_E76',   u: 'Stevens',               v: 'WilmerDavis',           weight: 79 });
  g.addEdge({ id: 'TEMPLATE_E77',   u: 'Avery',                 v: 'KimbroughMusic',        weight: 47 });
  g.addEdge({ id: 'TEMPLATE_E78',   u: 'VanDoren',              v: 'KimbroughMusic',        weight: 38 });
  g.addEdge({ id: 'TEMPLATE_E79',   u: 'VanDoren',              v: 'Avery',                 weight: 51 });
  g.addEdge({ id: 'TEMPLATE_E80',   u: 'Bryan',                 v: 'Avery',                 weight: 40 });
  g.addEdge({ id: 'TEMPLATE_E81',   u: 'Bryan',                 v: 'VanDoren',              weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E82',   u: 'Bryan',                 v: 'HallandLib',            weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E83',   u: 'Murrow',                v: 'Bryan',                 weight: 64 });
  g.addEdge({ id: 'TEMPLATE_E84',   u: 'TerrellLib',            v: 'HallandLib',            weight: 36 });
  g.addEdge({ id: 'TEMPLATE_E85',   u: 'VanDoren',              v: 'HallandLib',            weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E86',   u: 'Murrow',                v: 'HallandLib',            weight: 95 });
  g.addEdge({ id: 'TEMPLATE_E87',   u: 'Bryan',                 v: 'College',               weight: 88 });
  g.addEdge({ id: 'TEMPLATE_E88',   u: 'College',               v: 'HallandLib',            weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E89',   u: 'College',               v: 'TerrellLib',            weight: 77 });
  g.addEdge({ id: 'TEMPLATE_E90',   u: 'College',               v: 'Murrow',                weight: 77 });
  g.addEdge({ id: 'TEMPLATE_E91',   u: 'SloanHall',             v: 'Thompson',              weight: 110 });
  g.addEdge({ id: 'TEMPLATE_E92',   u: 'SloanHall',             v: 'Goertzen',              weight: 96 });
  g.addEdge({ id: 'TEMPLATE_E93',   u: 'SloanHall',             v: 'Morril',                weight: 109 });
  g.addEdge({ id: 'TEMPLATE_E94',   u: 'SloanHall',             v: 'Carpenter',             weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E95',   u: 'Goertzen',              v: 'Carpenter',             weight: 93 });
  g.addEdge({ id: 'TEMPLATE_E96',   u: 'Goertzen',              v: 'Daggy',                 weight: 96 });
  g.addEdge({ id: 'TEMPLATE_E97',   u: 'Daggy',                 v: 'Morril',                weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E98',   u: 'ChilledWater',          v: 'EngineeringResearch',   weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E99',   u: 'ChilledWater',          v: 'Carpenter',             weight: 133 });
  g.addEdge({ id: 'TEMPLATE_E100',  u: 'ChilledWater',          v: 'Daggy',                 weight: 140 });
  g.addEdge({ id: 'TEMPLATE_E101',  u: 'ChilledWater',          v: 'Cleveland',             weight: 185 });
  g.addEdge({ id: 'TEMPLATE_E102',  u: 'Daggy',                 v: 'Cleveland',             weight: 112 });
  g.addEdge({ id: 'TEMPLATE_E103',  u: 'MLA',                   v: 'Cleveland',             weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E104',  u: 'Heald',                 v: 'Cleveland',             weight: 67 });
  g.addEdge({ id: 'TEMPLATE_E105',  u: 'Heald',                 v: 'OwenSciEng',            weight: 73 });
  g.addEdge({ id: 'TEMPLATE_E106',  u: 'OwenSciEng',            v: 'Abelson',               weight: 72 });
  g.addEdge({ id: 'TEMPLATE_E107',  u: 'OwenSciEng',            v: 'Cleveland',             weight: 42 });
  g.addEdge({ id: 'TEMPLATE_E108',  u: 'Daggy',                 v: 'EducAdd',               weight: 130 });
  g.addEdge({ id: 'TEMPLATE_E109',  u: 'Dana',                  v: 'EducAdd',               weight: 185 });
  g.addEdge({ id: 'TEMPLATE_E110',  u: 'EngineeringResearch',   v: 'EducAdd',               weight: 208 });
  g.addEdge({ id: 'TEMPLATE_E111',  u: 'MLA',                   v: 'Eastlick',              weight: 51 });
  g.addEdge({ id: 'TEMPLATE_E112',  u: 'Eastlick',              v: 'Abelson',               weight: 44 });
  g.addEdge({ id: 'TEMPLATE_E113',  u: 'Eastlick',              v: 'Heald',                 weight: 35 });
  g.addEdge({ id: 'TEMPLATE_E114',  u: 'Morril',                v: 'Eastlick',              weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E115',  u: 'Eastlick',              v: 'Daggy',                 weight: 79 });
  g.addEdge({ id: 'TEMPLATE_E116',  u: 'Eastlick',              v: 'Murrow',                weight: 69 });
  g.addEdge({ id: 'TEMPLATE_E117',  u: 'Eastlick',              v: 'Goertzen',              weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E118',  u: 'Eastlick',              v: 'Jackson',               weight: 83 });
  g.addEdge({ id: 'TEMPLATE_E119',  u: 'Eastlick',              v: 'College',               weight: 103 });
  g.addEdge({ id: 'TEMPLATE_E130',  u: 'Murrow',                v: 'Todd',                  weight: 123 });
  g.addEdge({ id: 'TEMPLATE_E131',  u: 'Murrow',                v: 'Fulmer',                weight: 132 });
  g.addEdge({ id: 'TEMPLATE_E132',  u: 'Fulmer',                v: 'Todd',                  weight: 49 });
  g.addEdge({ id: 'TEMPLATE_E133',  u: 'Todd',                  v: 'FulmerSynthesis',       weight: 57 });
  g.addEdge({ id: 'TEMPLATE_E134',  u: 'Todd',                  v: 'JohnsonTower',          weight: 56 });
  g.addEdge({ id: 'TEMPLATE_E135',  u: 'Todd',                  v: 'WilsonShort',           weight: 79 });
  g.addEdge({ id: 'TEMPLATE_E136',  u: 'Todd',                  v: 'College',               weight: 58 });
  g.addEdge({ id: 'TEMPLATE_E137',  u: 'FulmerSynthesis',       v: 'Fulmer',                weight: 61 });
  g.addEdge({ id: 'TEMPLATE_E138',  u: 'FulmerSynthesis',       v: 'JohnsonTower',          weight: 48 });
  g.addEdge({ id: 'TEMPLATE_E139',  u: 'JohnsonTower',          v: 'Troy',                  weight: 39 });
  g.addEdge({ id: 'TEMPLATE_E140',  u: 'Troy',                  v: 'FulmerSynthesis',       weight: 28 });
  g.addEdge({ id: 'TEMPLATE_E141',  u: 'FulmerSynthesis',       v: 'WebsterPS',             weight: 48 });
  g.addEdge({ id: 'TEMPLATE_E142',  u: 'WebsterPS',             v: 'Fulmer',                weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E143',  u: 'Fulmer',                v: 'Stimson',               weight: 44 });
  g.addEdge({ id: 'TEMPLATE_E144',  u: 'Stimson',               v: 'FulmerSynthesis',       weight: 78 });
  g.addEdge({ id: 'TEMPLATE_E145',  u: 'Stimson',               v: 'OwenSciEng',            weight: 45 });
  g.addEdge({ id: 'TEMPLATE_E146',  u: 'Stimson',               v: 'Abelson',               weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E147',  u: 'Abelson',               v: 'Fulmer',                weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E148',  u: 'Abelson',               v: 'College',               weight: 92 });
  g.addEdge({ id: 'TEMPLATE_E149',  u: 'Abelson',               v: 'Murrow',                weight: 95 });
  g.addEdge({ id: 'TEMPLATE_E150',  u: 'Murrow',                v: 'Jackson',               weight: 29 });
  g.addEdge({ id: 'TEMPLATE_E151',  u: 'Jackson',               v: 'Avery',                 weight: 89 });
  g.addEdge({ id: 'TEMPLATE_E152',  u: 'Jackson',               v: 'Bryan',                 weight: 68 });
  g.addEdge({ id: 'TEMPLATE_E153',  u: 'Murrow',                v: 'Avery',                 weight: 96 });
  g.addEdge({ id: 'TEMPLATE_E154',  u: 'Murrow',                v: 'Morril',                weight: 63 });
  g.addEdge({ id: 'TEMPLATE_E155',  u: 'Morril',                v: 'Jackson',               weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E156',  u: 'Morril',                v: 'Goertzen',              weight: 37 });
  g.addEdge({ id: 'TEMPLATE_E157',  u: 'Thompson',              v: 'Bryan',                 weight: 82 });
  g.addEdge({ id: 'TEMPLATE_E158',  u: 'WebsterPS',             v: 'Troy',                  weight: 56 });
  g.addEdge({ id: 'TEMPLATE_E159',  u: 'Wegner',                v: 'Troy',                  weight: 115 });
  g.addEdge({ id: 'TEMPLATE_E160',  u: 'Troy',                  v: 'SmithCenter',           weight: 67 });
  g.addEdge({ id: 'TEMPLATE_E161',  u: 'JohnsonTower',          v: 'McCoy',                 weight: 168 });
  g.addEdge({ id: 'TEMPLATE_E162',  u: 'SmithCenter',           v: 'McCoy',                 weight: 140 });
  g.addEdge({ id: 'TEMPLATE_E163',  u: 'McCoy',                 v: 'Troy',                  weight: 140 });
  g.addEdge({ id: 'TEMPLATE_E164',  u: 'McCoy',                 v: 'FineArtsCenter',        weight: 150 });
  g.addEdge({ id: 'TEMPLATE_E165',  u: 'McCoy',                 v: 'Schnitzer',             weight: 180 });
  g.addEdge({ id: 'TEMPLATE_E166',  u: 'WilsonShort',           v: 'JohnsonTower',          weight: 49 });
  g.addEdge({ id: 'TEMPLATE_E167',  u: 'WilsonShort',           v: 'SmithCenter',           weight: 61 });
  g.addEdge({ id: 'TEMPLATE_E168',  u: 'WilsonShort',           v: 'Schnitzer',             weight: 53 });
  g.addEdge({ id: 'TEMPLATE_E169',  u: 'Schnitzer',             v: 'SmithCenter',           weight: 49 });
  g.addEdge({ id: 'TEMPLATE_E170',  u: 'SmithCenter',           v: 'FineArtsCenter',        weight: 76 });
  g.addEdge({ id: 'TEMPLATE_E171',  u: 'JohnsonTower',          v: 'SmithCenter',           weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E172',  u: 'Wegner',                v: 'SmithCenter',           weight: 139 });
  g.addEdge({ id: 'TEMPLATE_E173',  u: 'Bustad',                v: 'FineArtsCenter',        weight: 119 });
  g.addEdge({ id: 'TEMPLATE_E174',  u: 'VeterinaryTeaching',    v: 'McCoy',                 weight: 94 });
  g.addEdge({ id: 'TEMPLATE_E175',  u: 'Bustad',                v: 'FrenchAdmin',           weight: 147 });
  g.addEdge({ id: 'TEMPLATE_E176',  u: 'FrenchAdmin',           v: 'FineArtsCenter',        weight: 102 });
  g.addEdge({ id: 'TEMPLATE_E177',  u: 'FrenchAdmin',           v: 'LightySS',              weight: 38 });
  g.addEdge({ id: 'TEMPLATE_E178',  u: 'Bustad',                v: 'LightySS',              weight: 164 });
  g.addEdge({ id: 'TEMPLATE_E179',  u: 'LightySS',              v: 'GrimesWay',             weight: 76 });
  g.addEdge({ id: 'TEMPLATE_E180',  u: 'GrimesWay',             v: 'USDAAgri',              weight: 67 });
  g.addEdge({ id: 'TEMPLATE_E181',  u: 'GrimesWay',             v: 'PaccarEnvTech',         weight: 86 });
  g.addEdge({ id: 'TEMPLATE_E182',  u: 'LightySS',              v: 'Johnson',               weight: 79 });
  g.addEdge({ id: 'TEMPLATE_E183',  u: 'FrenchAdmin',           v: 'VogelPlant',            weight: 98 });
  g.addEdge({ id: 'TEMPLATE_E184',  u: 'FrenchAdmin',           v: 'IT',                    weight: 82 });
  g.addEdge({ id: 'TEMPLATE_E185',  u: 'VogelPlant',            v: 'LightySS',              weight: 109 });
  g.addEdge({ id: 'TEMPLATE_E186',  u: 'Johnson',               v: 'FrenchAdmin',           weight: 85 });
  g.addEdge({ id: 'TEMPLATE_E187',  u: 'Johnson',               v: 'VogelPlant',            weight: 45 });
  g.addEdge({ id: 'TEMPLATE_E188',  u: 'Johnson',               v: 'GrimesWay',             weight: 122 });
  g.addEdge({ id: 'TEMPLATE_E189',  u: 'Hulbert',               v: 'Clark',                 weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E190',  u: 'Clark',                 v: 'PlantSciences',         weight: 59 });
  g.addEdge({ id: 'TEMPLATE_E191',  u: 'Johnson',               v: 'PlantSciences',         weight: 85 });
  g.addEdge({ id: 'TEMPLATE_E192',  u: 'PlantSciences',         v: 'VogelPlant',            weight: 96 });
  g.addEdge({ id: 'TEMPLATE_E193',  u: 'VogelPlant',            v: 'IT',                    weight: 78 });
  g.addEdge({ id: 'TEMPLATE_E194',  u: 'VogelPlant',            v: 'MartinStadium',         weight: 105 });
  g.addEdge({ id: 'TEMPLATE_E195',  u: 'MartinStadium',         v: 'Biotechnology',         weight: 142 });
  g.addEdge({ id: 'TEMPLATE_E196',  u: 'MooberryTrack',         v: 'MartinStadium',         weight: 119 });
  g.addEdge({ id: 'TEMPLATE_E197',  u: 'BohlerGym',             v: 'MartinStadium',         weight: 117 });
  g.addEdge({ id: 'TEMPLATE_E198',  u: 'BohlerGym',             v: 'RogersField',           weight: 76 });
  g.addEdge({ id: 'TEMPLATE_E199',  u: 'CUB',                   v: 'RogersField',           weight: 72 });
  g.addEdge({ id: 'TEMPLATE_E200',  u: 'CUB',                   v: 'TerrellLib',            weight: 43 });
  g.addEdge({ id: 'TEMPLATE_E201',  u: 'RogersField',           v: 'PhysicalEdu',           weight: 82 });
  g.addEdge({ id: 'TEMPLATE_E202',  u: 'RogersField',           v: 'SmithGym',              weight: 105 });
  g.addEdge({ id: 'TEMPLATE_E203',  u: 'RogersField',           v: 'ChinookStudentCenter',  weight: 150 });
  g.addEdge({ id: 'TEMPLATE_E204',  u: 'SmithGym',              v: 'KimbroughMusic',        weight: 63 });
  g.addEdge({ id: 'TEMPLATE_E205',  u: 'SmithGym',              v: 'VanDoren',              weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E206',  u: 'SmithGym',              v: 'HallandLib',            weight: 133 });
  g.addEdge({ id: 'TEMPLATE_E207',  u: 'BohlerGym',             v: 'PhysicalEdu',           weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E208',  u: 'PlantSciences',         v: 'Biotechnology',         weight: 56 });
  g.addEdge({ id: 'TEMPLATE_E209',  u: 'VeterinaryBiomedical',  v: 'PlantSciences',         weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E210',  u: 'Clark',                 v: 'FoodScience',           weight: 44 });
  g.addEdge({ id: 'TEMPLATE_E211',  u: 'FoodScience',           v: 'PlantSciences',         weight: 67 });
  g.addEdge({ id: 'TEMPLATE_E212',  u: 'FoodScience',           v: 'Biotechnology',         weight: 114 });
  g.addEdge({ id: 'TEMPLATE_E213',  u: 'College',               v: 'CUB',                   weight: 99 });
  g.addEdge({ id: 'TEMPLATE_E214',  u: 'CUB',                   v: 'WilsonShort',           weight: 60 });
  g.addEdge({ id: 'TEMPLATE_E215',  u: 'Todd',                  v: 'CUB',                   weight: 117 });
  g.addEdge({ id: 'TEMPLATE_E216',  u: 'Todd',                  v: 'TerrellLib',            weight: 117 });
  g.addEdge({ id: 'TEMPLATE_E217',  u: 'TerrellLib',            v: 'WilsonShort',           weight: 88 });
  g.addEdge({ id: 'TEMPLATE_E218',  u: 'CUB',                   v: 'Schnitzer',             weight: 81 });
  g.addEdge({ id: 'TEMPLATE_E219',  u: 'Schnitzer',             v: 'FineArtsCenter',        weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E220',  u: 'Schnitzer',             v: 'IT',                    weight: 106 });
  g.addEdge({ id: 'TEMPLATE_E221',  u: 'IT',                    v: 'FineArtsCenter',        weight: 80 });
  g.addEdge({ id: 'TEMPLATE_E222',  u: 'Clark',                 v: 'FoodQuality',           weight: 75 });
  g.addEdge({ id: 'TEMPLATE_E223',  u: 'LightySS',              v: 'Clark',                 weight: 160 });
  g.addEdge({ id: 'TEMPLATE_E224',  u: 'Clark',                 v: 'Johnson',               weight: 108 });
  g.addEdge({ id: 'TEMPLATE_E225',  u: 'Johnson',               v: 'Hulbert',               weight: 131 });
  g.addEdge({ id: 'TEMPLATE_E226',  u: 'PlantSciences',         v: 'GrimesWay',             weight: 173 });
  g.addEdge({ id: 'TEMPLATE_E227',  u: 'Bustad',                v: 'GrimesWay',             weight: 208 });
  g.addEdge({ id: 'TEMPLATE_E228',  u: 'KimbroughMusic',        v: 'ChinookStudentCenter',  weight: 50 });
  g.addEdge({ id: 'TEMPLATE_E229',  u: 'VanDoren',              v: 'PhysicalEdu',           weight: 102 });
  g.addEdge({ id: 'TEMPLATE_E230',  u: 'McCroskeyHall',         v: 'ChinookStudentCenter',  weight: 105 });
  g.addEdge({ id: 'TEMPLATE_E231',  u: 'Stevens',               v: 'ChinookStudentCenter',  weight: 100 });
  g.addEdge({ id: 'TEMPLATE_E232',  u: 'Avery',                 v: 'WilmerDavis',           weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E233',  u: 'DuncanDunn',            v: 'Thompson',              weight: 125 });
  g.addEdge({ id: 'TEMPLATE_E234',  u: 'CUB',                   v: 'MartinStadium',         weight: 129 });

  return g;
}
