import { createGraph } from '../models/graph.js';

export const MAP_WIDTH = 1024;
export const MAP_HEIGHT = 512;

export function createCampusGraph() {
  const g = createGraph();

  // TEMPLATE VERTICES
  g.addVertex({ id: 'TEMPLATE_1', name: 'TEMPLATE', x: 135, y: 318, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_2', name: 'TEMPLATE', x: 150, y: 202, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_3', name: 'TEMPLATE', x: 247, y: 226, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_4', name: 'TEMPLATE', x: 214, y: 257, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_5', name: 'TEMPLATE', x: 194, y: 315, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_6', name: 'TEMPLATE', x: 206, y: 131, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_7', name: 'TEMPLATE', x: 290, y: 153, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_8', name: 'TEMPLATE', x: 354, y: 128, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_9', name: 'TEMPLATE', x: 323, y: 71, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_10', name: 'TEMPLATE', x: 367, y: 75, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_11', name: 'TEMPLATE', x: 390, y: 151, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_12', name: 'TEMPLATE', x: 419, y: 145, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_13', name: 'TEMPLATE', x: 433, y: 183, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_14', name: 'TEMPLATE', x: 352, y: 193, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_15', name: 'TEMPLATE', x: 343, y: 232, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_16', name: 'TEMPLATE', x: 403, y: 240, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_17', name: 'TEMPLATE', x: 347, y: 269, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_18', name: 'TEMPLATE', x: 470, y: 143, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_19', name: 'TEMPLATE', x: 451, y: 110, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_20', name: 'TEMPLATE', x: 436, y: 62, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_21', name: 'TEMPLATE', x: 492, y: 62, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_22', name: 'TEMPLATE', x: 587, y: 65, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_23', name: 'TEMPLATE', x: 587, y: 30, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_24', name: 'TEMPLATE', x: 637, y: 60, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_25', name: 'TEMPLATE', x: 684, y: 24, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_26', name: 'TEMPLATE', x: 674, y: 143, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_27', name: 'TEMPLATE', x: 565, y: 138, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_28', name: 'TEMPLATE', x: 717, y: 214, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_29', name: 'TEMPLATE', x: 564, y: 210, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_30', name: 'TEMPLATE', x: 487, y: 195, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_31', name: 'TEMPLATE', x: 478, y: 259, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_32', name: 'TEMPLATE', x: 504, y: 311, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_33', name: 'TEMPLATE', x: 560, y: 318, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_34', name: 'TEMPLATE', x: 624, y: 265, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_35', name: 'TEMPLATE', x: 614, y: 313, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_36', name: 'TEMPLATE', x: 685, y: 287, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_37', name: 'TEMPLATE', x: 571, y: 270, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_38', name: 'TEMPLATE', x: 475, y: 351, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_39', name: 'TEMPLATE', x: 535, y: 359, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_40', name: 'TEMPLATE', x: 538, y: 407, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_41', name: 'TEMPLATE', x: 465, y: 394, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_42', name: 'TEMPLATE', x: 379, y: 409, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_43', name: 'TEMPLATE', x: 404, y: 456, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_44', name: 'TEMPLATE', x: 282, y: 302, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_45', name: 'TEMPLATE', x: 240, y: 300, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_46', name: 'TEMPLATE', x: 194, y: 402, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_47', name: 'TEMPLATE', x: 166, y: 323, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_48', name: 'TEMPLATE', x: 162, y: 270, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_49', name: 'TEMPLATE', x: 309, y: 322, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_50', name: 'TEMPLATE', x: 387, y: 307, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_51', name: 'TEMPLATE', x: 359, y: 442, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_52', name: 'TEMPLATE', x: 421, y: 405, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_53', name: 'TEMPLATE', x: 385, y: 342, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_54', name: 'TEMPLATE', x: 423, y: 333, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_55', name: 'TEMPLATE', x: 343, y: 333, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_56', name: 'TEMPLATE', x: 379, y: 224, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_59', name: 'TEMPLATE', x: 765, y: 473, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_60', name: 'TEMPLATE', x: 729, y: 398, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_61', name: 'TEMPLATE', x: 678, y: 437, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_62', name: 'TEMPLATE', x: 629, y: 451, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_63', name: 'TEMPLATE', x: 563, y: 357, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_64', name: 'TEMPLATE', x: 523, y: 196, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_65', name: 'TEMPLATE', x: 897, y: 276, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_66', name: 'TEMPLATE', x: 784, y: 262, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_67', name: 'TEMPLATE', x: 822, y: 263, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_68', name: 'TEMPLATE', x: 817, y: 184, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_69', name: 'TEMPLATE', x: 777, y: 164, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_70', name: 'TEMPLATE', x: 851, y: 54, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_71', name: 'TEMPLATE', x: 804, y: 86, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_72', name: 'TEMPLATE', x: 855, y: 108, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_73', name: 'TEMPLATE', x: 910, y: 129, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_74', name: 'TEMPLATE', x: 947, y: 169, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_76', name: 'TEMPLATE', x: 918, y: 86, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_77', name: 'TEMPLATE', x: 969, y: 83, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_78', name: 'TEMPLATE', x: 960, y: 335, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_79', name: 'TEMPLATE', x: 962, y: 292, isTerminal: false });
  g.addVertex({ id: 'TEMPLATE_81', name: 'TEMPLATE', x: 533, y: 63, isTerminal: false });



  // TEMPLATE EDGES
  g.addEdge({ id: 'TEMPLATE_E1', u: 'TEMPLATE_6', v: 'TEMPLATE_9', weight: 131 });
  g.addEdge({ id: 'TEMPLATE_E2', u: 'TEMPLATE_7', v: 'TEMPLATE_9', weight: 88 });
  g.addEdge({ id: 'TEMPLATE_E3', u: 'TEMPLATE_7', v: 'TEMPLATE_6', weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E4', u: 'TEMPLATE_7', v: 'TEMPLATE_8', weight: 69 });
  g.addEdge({ id: 'TEMPLATE_E5', u: 'TEMPLATE_7', v: 'TEMPLATE_10', weight: 110 });
  g.addEdge({ id: 'TEMPLATE_E6', u: 'TEMPLATE_7', v: 'TEMPLATE_14', weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E7', u: 'TEMPLATE_7', v: 'TEMPLATE_15', weight: 95 });
  g.addEdge({ id: 'TEMPLATE_E8', u: 'TEMPLATE_17', v: 'TEMPLATE_7', weight: 129 });
  g.addEdge({ id: 'TEMPLATE_E9', u: 'TEMPLATE_7', v: 'TEMPLATE_3', weight: 85 });
  g.addEdge({ id: 'TEMPLATE_E10', u: 'TEMPLATE_44', v: 'TEMPLATE_7', weight: 149 });
  g.addEdge({ id: 'TEMPLATE_E11', u: 'TEMPLATE_49', v: 'TEMPLATE_7', weight: 170 });
  g.addEdge({ id: 'TEMPLATE_E12', u: 'TEMPLATE_7', v: 'TEMPLATE_11', weight: 100 });
  g.addEdge({ id: 'TEMPLATE_E13', u: 'TEMPLATE_7', v: 'TEMPLATE_2', weight: 148 });
  g.addEdge({ id: 'TEMPLATE_E14', u: 'TEMPLATE_8', v: 'TEMPLATE_10', weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E15', u: 'TEMPLATE_8', v: 'TEMPLATE_9', weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E16', u: 'TEMPLATE_8', v: 'TEMPLATE_11', weight: 43 });
  g.addEdge({ id: 'TEMPLATE_E17', u: 'TEMPLATE_8', v: 'TEMPLATE_14', weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E18', u: 'TEMPLATE_11', v: 'TEMPLATE_12', weight: 30 });
  g.addEdge({ id: 'TEMPLATE_E19', u: 'TEMPLATE_11', v: 'TEMPLATE_13', weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E20', u: 'TEMPLATE_11', v: 'TEMPLATE_14', weight: 57 });
  g.addEdge({ id: 'TEMPLATE_E21', u: 'TEMPLATE_11', v: 'TEMPLATE_56', weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E22', u: 'TEMPLATE_11', v: 'TEMPLATE_16', weight: 90 });
  g.addEdge({ id: 'TEMPLATE_E23', u: 'TEMPLATE_10', v: 'TEMPLATE_9', weight: 44 });
  g.addEdge({ id: 'TEMPLATE_E24', u: 'TEMPLATE_10', v: 'TEMPLATE_20', weight: 70 });
  g.addEdge({ id: 'TEMPLATE_E25', u: 'TEMPLATE_10', v: 'TEMPLATE_19', weight: 91 });
  g.addEdge({ id: 'TEMPLATE_E26', u: 'TEMPLATE_6', v: 'TEMPLATE_3', weight: 103 });
  g.addEdge({ id: 'TEMPLATE_E27', u: 'TEMPLATE_6', v: 'TEMPLATE_2', weight: 90 });
  g.addEdge({ id: 'TEMPLATE_E28', u: 'TEMPLATE_6', v: 'TEMPLATE_48', weight: 146 });
  g.addEdge({ id: 'TEMPLATE_E29', u: 'TEMPLATE_2', v: 'TEMPLATE_48', weight: 69 });
  g.addEdge({ id: 'TEMPLATE_E30', u: 'TEMPLATE_2', v: 'TEMPLATE_4', weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E31', u: 'TEMPLATE_4', v: 'TEMPLATE_3', weight: 45 });
  g.addEdge({ id: 'TEMPLATE_E32', u: 'TEMPLATE_4', v: 'TEMPLATE_45', weight: 50 });
  g.addEdge({ id: 'TEMPLATE_E33', u: 'TEMPLATE_45', v: 'TEMPLATE_3', weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E34', u: 'TEMPLATE_4', v: 'TEMPLATE_5', weight: 61 });
  g.addEdge({ id: 'TEMPLATE_E35', u: 'TEMPLATE_5', v: 'TEMPLATE_45', weight: 48 });
  g.addEdge({ id: 'TEMPLATE_E36', u: 'TEMPLATE_4', v: 'TEMPLATE_48', weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E37', u: 'TEMPLATE_48', v: 'TEMPLATE_1', weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E38', u: 'TEMPLATE_48', v: 'TEMPLATE_47', weight: 53 });
  g.addEdge({ id: 'TEMPLATE_E39', u: 'TEMPLATE_47', v: 'TEMPLATE_1', weight: 31 });
  g.addEdge({ id: 'TEMPLATE_E40', u: 'TEMPLATE_47', v: 'TEMPLATE_5', weight: 29 });
  g.addEdge({ id: 'TEMPLATE_E41', u: 'TEMPLATE_5', v: 'TEMPLATE_48', weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E42', u: 'TEMPLATE_45', v: 'TEMPLATE_44', weight: 42 });
  g.addEdge({ id: 'TEMPLATE_E43', u: 'TEMPLATE_44', v: 'TEMPLATE_49', weight: 34 });
  g.addEdge({ id: 'TEMPLATE_E44', u: 'TEMPLATE_49', v: 'TEMPLATE_55', weight: 36 });
  g.addEdge({ id: 'TEMPLATE_E45', u: 'TEMPLATE_55', v: 'TEMPLATE_53', weight: 43 });
  g.addEdge({ id: 'TEMPLATE_E46', u: 'TEMPLATE_53', v: 'TEMPLATE_54', weight: 39 });
  g.addEdge({ id: 'TEMPLATE_E47', u: 'TEMPLATE_47', v: 'TEMPLATE_46', weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E48', u: 'TEMPLATE_46', v: 'TEMPLATE_51', weight: 170 });
  g.addEdge({ id: 'TEMPLATE_E49', u: 'TEMPLATE_51', v: 'TEMPLATE_42', weight: 39 });
  g.addEdge({ id: 'TEMPLATE_E50', u: 'TEMPLATE_42', v: 'TEMPLATE_43', weight: 53 });
  g.addEdge({ id: 'TEMPLATE_E51', u: 'TEMPLATE_43', v: 'TEMPLATE_52', weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E52', u: 'TEMPLATE_51', v: 'TEMPLATE_43', weight: 47 });
  g.addEdge({ id: 'TEMPLATE_E53', u: 'TEMPLATE_43', v: 'TEMPLATE_41', weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E54', u: 'TEMPLATE_41', v: 'TEMPLATE_40', weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E55', u: 'TEMPLATE_40', v: 'TEMPLATE_62', weight: 101 });
  g.addEdge({ id: 'TEMPLATE_E56', u: 'TEMPLATE_62', v: 'TEMPLATE_61', weight: 51 });
  g.addEdge({ id: 'TEMPLATE_E57', u: 'TEMPLATE_61', v: 'TEMPLATE_60', weight: 64 });
  g.addEdge({ id: 'TEMPLATE_E58', u: 'TEMPLATE_60', v: 'TEMPLATE_59', weight: 83 });
  g.addEdge({ id: 'TEMPLATE_E59', u: 'TEMPLATE_59', v: 'TEMPLATE_78', weight: 239 });
  g.addEdge({ id: 'TEMPLATE_E60', u: 'TEMPLATE_78', v: 'TEMPLATE_79', weight: 43 });
  g.addEdge({ id: 'TEMPLATE_E61', u: 'TEMPLATE_79', v: 'TEMPLATE_74', weight: 124 });
  g.addEdge({ id: 'TEMPLATE_E63', u: 'TEMPLATE_77', v: 'TEMPLATE_76', weight: 51 });
  g.addEdge({ id: 'TEMPLATE_E64', u: 'TEMPLATE_76', v: 'TEMPLATE_70', weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E65', u: 'TEMPLATE_70', v: 'TEMPLATE_71', weight: 57 });
  g.addEdge({ id: 'TEMPLATE_E66', u: 'TEMPLATE_71', v: 'TEMPLATE_25', weight: 135 });
  g.addEdge({ id: 'TEMPLATE_E67', u: 'TEMPLATE_25', v: 'TEMPLATE_24', weight: 59 });
  g.addEdge({ id: 'TEMPLATE_E68', u: 'TEMPLATE_24', v: 'TEMPLATE_22', weight: 50 });
  g.addEdge({ id: 'TEMPLATE_E69', u: 'TEMPLATE_22', v: 'TEMPLATE_23', weight: 35 });
  g.addEdge({ id: 'TEMPLATE_E70', u: 'TEMPLATE_23', v: 'TEMPLATE_81', weight: 63 });
  g.addEdge({ id: 'TEMPLATE_E71', u: 'TEMPLATE_81', v: 'TEMPLATE_21', weight: 41 });
  g.addEdge({ id: 'TEMPLATE_E72', u: 'TEMPLATE_21', v: 'TEMPLATE_20', weight: 56 });
  g.addEdge({ id: 'TEMPLATE_E73', u: 'TEMPLATE_56', v: 'TEMPLATE_15', weight: 37 });
  g.addEdge({ id: 'TEMPLATE_E74', u: 'TEMPLATE_14', v: 'TEMPLATE_15', weight: 40 });
  g.addEdge({ id: 'TEMPLATE_E75', u: 'TEMPLATE_56', v: 'TEMPLATE_14', weight: 41 });
  g.addEdge({ id: 'TEMPLATE_E76', u: 'TEMPLATE_11', v: 'TEMPLATE_10', weight: 79 });
  g.addEdge({ id: 'TEMPLATE_E77', u: 'TEMPLATE_12', v: 'TEMPLATE_19', weight: 47 });
  g.addEdge({ id: 'TEMPLATE_E78', u: 'TEMPLATE_18', v: 'TEMPLATE_19', weight: 38 });
  g.addEdge({ id: 'TEMPLATE_E79', u: 'TEMPLATE_18', v: 'TEMPLATE_12', weight: 51 });
  g.addEdge({ id: 'TEMPLATE_E80', u: 'TEMPLATE_13', v: 'TEMPLATE_12', weight: 40 });
  g.addEdge({ id: 'TEMPLATE_E81', u: 'TEMPLATE_13', v: 'TEMPLATE_18', weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E82', u: 'TEMPLATE_13', v: 'TEMPLATE_30', weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E83', u: 'TEMPLATE_16', v: 'TEMPLATE_13', weight: 64 });
  g.addEdge({ id: 'TEMPLATE_E84', u: 'TEMPLATE_64', v: 'TEMPLATE_30', weight: 36 });
  g.addEdge({ id: 'TEMPLATE_E85', u: 'TEMPLATE_18', v: 'TEMPLATE_30', weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E86', u: 'TEMPLATE_16', v: 'TEMPLATE_30', weight: 95 });
  g.addEdge({ id: 'TEMPLATE_E87', u: 'TEMPLATE_13', v: 'TEMPLATE_31', weight: 88 });
  g.addEdge({ id: 'TEMPLATE_E88', u: 'TEMPLATE_31', v: 'TEMPLATE_30', weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E89', u: 'TEMPLATE_31', v: 'TEMPLATE_64', weight: 77 });
  g.addEdge({ id: 'TEMPLATE_E90', u: 'TEMPLATE_31', v: 'TEMPLATE_16', weight: 77 });
  g.addEdge({ id: 'TEMPLATE_E91', u: 'TEMPLATE_3', v: 'TEMPLATE_14', weight: 110 });
  g.addEdge({ id: 'TEMPLATE_E92', u: 'TEMPLATE_3', v: 'TEMPLATE_15', weight: 96 });
  g.addEdge({ id: 'TEMPLATE_E93', u: 'TEMPLATE_3', v: 'TEMPLATE_17', weight: 109 });
  g.addEdge({ id: 'TEMPLATE_E94', u: 'TEMPLATE_3', v: 'TEMPLATE_44', weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E95', u: 'TEMPLATE_15', v: 'TEMPLATE_44', weight: 93 });
  g.addEdge({ id: 'TEMPLATE_E96', u: 'TEMPLATE_15', v: 'TEMPLATE_49', weight: 96 });
  g.addEdge({ id: 'TEMPLATE_E97', u: 'TEMPLATE_49', v: 'TEMPLATE_17', weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E98', u: 'TEMPLATE_46', v: 'TEMPLATE_5', weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E99', u: 'TEMPLATE_46', v: 'TEMPLATE_44', weight: 133 });
  g.addEdge({ id: 'TEMPLATE_E100', u: 'TEMPLATE_46', v: 'TEMPLATE_49', weight: 140 });
  g.addEdge({ id: 'TEMPLATE_E101', u: 'TEMPLATE_46', v: 'TEMPLATE_42', weight: 185 });
  g.addEdge({ id: 'TEMPLATE_E102', u: 'TEMPLATE_49', v: 'TEMPLATE_42', weight: 112 });
  g.addEdge({ id: 'TEMPLATE_E103', u: 'TEMPLATE_55', v: 'TEMPLATE_42', weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E104', u: 'TEMPLATE_53', v: 'TEMPLATE_42', weight: 67 });
  g.addEdge({ id: 'TEMPLATE_E105', u: 'TEMPLATE_53', v: 'TEMPLATE_52', weight: 73 });
  g.addEdge({ id: 'TEMPLATE_E106', u: 'TEMPLATE_52', v: 'TEMPLATE_54', weight: 72 });
  g.addEdge({ id: 'TEMPLATE_E107', u: 'TEMPLATE_52', v: 'TEMPLATE_42', weight: 42 });
  g.addEdge({ id: 'TEMPLATE_E108', u: 'TEMPLATE_49', v: 'TEMPLATE_51', weight: 130 });
  g.addEdge({ id: 'TEMPLATE_E109', u: 'TEMPLATE_45', v: 'TEMPLATE_51', weight: 185 });
  g.addEdge({ id: 'TEMPLATE_E110', u: 'TEMPLATE_5', v: 'TEMPLATE_51', weight: 208 });
  g.addEdge({ id: 'TEMPLATE_E111', u: 'TEMPLATE_55', v: 'TEMPLATE_50', weight: 51 });
  g.addEdge({ id: 'TEMPLATE_E112', u: 'TEMPLATE_50', v: 'TEMPLATE_54', weight: 44 });
  g.addEdge({ id: 'TEMPLATE_E113', u: 'TEMPLATE_50', v: 'TEMPLATE_53', weight: 35 });
  g.addEdge({ id: 'TEMPLATE_E114', u: 'TEMPLATE_17', v: 'TEMPLATE_50', weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E115', u: 'TEMPLATE_50', v: 'TEMPLATE_49', weight: 79 });
  g.addEdge({ id: 'TEMPLATE_E116', u: 'TEMPLATE_50', v: 'TEMPLATE_16', weight: 69 });
  g.addEdge({ id: 'TEMPLATE_E117', u: 'TEMPLATE_50', v: 'TEMPLATE_15', weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E118', u: 'TEMPLATE_50', v: 'TEMPLATE_56', weight: 83 });
  g.addEdge({ id: 'TEMPLATE_E119', u: 'TEMPLATE_50', v: 'TEMPLATE_31', weight: 103 });
  g.addEdge({ id: 'TEMPLATE_E130', u: 'TEMPLATE_16', v: 'TEMPLATE_32', weight: 123 });
  g.addEdge({ id: 'TEMPLATE_E131', u: 'TEMPLATE_16', v: 'TEMPLATE_38', weight: 132 });
  g.addEdge({ id: 'TEMPLATE_E132', u: 'TEMPLATE_38', v: 'TEMPLATE_32', weight: 49 });
  g.addEdge({ id: 'TEMPLATE_E133', u: 'TEMPLATE_32', v: 'TEMPLATE_39', weight: 57 });
  g.addEdge({ id: 'TEMPLATE_E134', u: 'TEMPLATE_32', v: 'TEMPLATE_33', weight: 56 });
  g.addEdge({ id: 'TEMPLATE_E135', u: 'TEMPLATE_32', v: 'TEMPLATE_37', weight: 79 });
  g.addEdge({ id: 'TEMPLATE_E136', u: 'TEMPLATE_32', v: 'TEMPLATE_31', weight: 58 });
  g.addEdge({ id: 'TEMPLATE_E137', u: 'TEMPLATE_39', v: 'TEMPLATE_38', weight: 61 });
  g.addEdge({ id: 'TEMPLATE_E138', u: 'TEMPLATE_39', v: 'TEMPLATE_33', weight: 48 });
  g.addEdge({ id: 'TEMPLATE_E139', u: 'TEMPLATE_33', v: 'TEMPLATE_63', weight: 39 });
  g.addEdge({ id: 'TEMPLATE_E140', u: 'TEMPLATE_63', v: 'TEMPLATE_39', weight: 28 });
  g.addEdge({ id: 'TEMPLATE_E141', u: 'TEMPLATE_39', v: 'TEMPLATE_40', weight: 48 });
  g.addEdge({ id: 'TEMPLATE_E142', u: 'TEMPLATE_40', v: 'TEMPLATE_38', weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E143', u: 'TEMPLATE_38', v: 'TEMPLATE_41', weight: 44 });
  g.addEdge({ id: 'TEMPLATE_E144', u: 'TEMPLATE_41', v: 'TEMPLATE_39', weight: 78 });
  g.addEdge({ id: 'TEMPLATE_E145', u: 'TEMPLATE_41', v: 'TEMPLATE_52', weight: 45 });
  g.addEdge({ id: 'TEMPLATE_E146', u: 'TEMPLATE_41', v: 'TEMPLATE_54', weight: 74 });
  g.addEdge({ id: 'TEMPLATE_E147', u: 'TEMPLATE_54', v: 'TEMPLATE_38', weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E148', u: 'TEMPLATE_54', v: 'TEMPLATE_31', weight: 92 });
  g.addEdge({ id: 'TEMPLATE_E149', u: 'TEMPLATE_54', v: 'TEMPLATE_16', weight: 95 });
  g.addEdge({ id: 'TEMPLATE_E150', u: 'TEMPLATE_16', v: 'TEMPLATE_56', weight: 29 });
  g.addEdge({ id: 'TEMPLATE_E151', u: 'TEMPLATE_56', v: 'TEMPLATE_12', weight: 89 });
  g.addEdge({ id: 'TEMPLATE_E152', u: 'TEMPLATE_56', v: 'TEMPLATE_13', weight: 68 });
  g.addEdge({ id: 'TEMPLATE_E153', u: 'TEMPLATE_16', v: 'TEMPLATE_12', weight: 96 });
  g.addEdge({ id: 'TEMPLATE_E154', u: 'TEMPLATE_16', v: 'TEMPLATE_17', weight: 63 });
  g.addEdge({ id: 'TEMPLATE_E155', u: 'TEMPLATE_17', v: 'TEMPLATE_56', weight: 55 });
  g.addEdge({ id: 'TEMPLATE_E156', u: 'TEMPLATE_17', v: 'TEMPLATE_15', weight: 37 });
  g.addEdge({ id: 'TEMPLATE_E157', u: 'TEMPLATE_14', v: 'TEMPLATE_13', weight: 82 });
  g.addEdge({ id: 'TEMPLATE_E158', u: 'TEMPLATE_40', v: 'TEMPLATE_63', weight: 56 });
  g.addEdge({ id: 'TEMPLATE_E159', u: 'TEMPLATE_62', v: 'TEMPLATE_63', weight: 115 });
  g.addEdge({ id: 'TEMPLATE_E160', u: 'TEMPLATE_63', v: 'TEMPLATE_35', weight: 67 });
  g.addEdge({ id: 'TEMPLATE_E161', u: 'TEMPLATE_33', v: 'TEMPLATE_61', weight: 168 });
  g.addEdge({ id: 'TEMPLATE_E162', u: 'TEMPLATE_35', v: 'TEMPLATE_61', weight: 140 });
  g.addEdge({ id: 'TEMPLATE_E163', u: 'TEMPLATE_61', v: 'TEMPLATE_63', weight: 140 });
  g.addEdge({ id: 'TEMPLATE_E164', u: 'TEMPLATE_61', v: 'TEMPLATE_36', weight: 150 });
  g.addEdge({ id: 'TEMPLATE_E165', u: 'TEMPLATE_61', v: 'TEMPLATE_34', weight: 180 });
  g.addEdge({ id: 'TEMPLATE_E166', u: 'TEMPLATE_37', v: 'TEMPLATE_33', weight: 49 });
  g.addEdge({ id: 'TEMPLATE_E167', u: 'TEMPLATE_37', v: 'TEMPLATE_35', weight: 61 });
  g.addEdge({ id: 'TEMPLATE_E168', u: 'TEMPLATE_37', v: 'TEMPLATE_34', weight: 53 });
  g.addEdge({ id: 'TEMPLATE_E169', u: 'TEMPLATE_34', v: 'TEMPLATE_35', weight: 49 });
  g.addEdge({ id: 'TEMPLATE_E170', u: 'TEMPLATE_35', v: 'TEMPLATE_36', weight: 76 });
  g.addEdge({ id: 'TEMPLATE_E171', u: 'TEMPLATE_33', v: 'TEMPLATE_35', weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E172', u: 'TEMPLATE_62', v: 'TEMPLATE_35', weight: 139 });
  g.addEdge({ id: 'TEMPLATE_E173', u: 'TEMPLATE_60', v: 'TEMPLATE_36', weight: 119 });
  g.addEdge({ id: 'TEMPLATE_E174', u: 'TEMPLATE_59', v: 'TEMPLATE_61', weight: 94 });
  g.addEdge({ id: 'TEMPLATE_E175', u: 'TEMPLATE_60', v: 'TEMPLATE_66', weight: 147 });
  g.addEdge({ id: 'TEMPLATE_E176', u: 'TEMPLATE_66', v: 'TEMPLATE_36', weight: 102 });
  g.addEdge({ id: 'TEMPLATE_E177', u: 'TEMPLATE_66', v: 'TEMPLATE_67', weight: 38 });
  g.addEdge({ id: 'TEMPLATE_E178', u: 'TEMPLATE_60', v: 'TEMPLATE_67', weight: 164 });
  g.addEdge({ id: 'TEMPLATE_E179', u: 'TEMPLATE_67', v: 'TEMPLATE_65', weight: 76 });
  g.addEdge({ id: 'TEMPLATE_E180', u: 'TEMPLATE_65', v: 'TEMPLATE_79', weight: 67 });
  g.addEdge({ id: 'TEMPLATE_E181', u: 'TEMPLATE_65', v: 'TEMPLATE_78', weight: 86 });
  g.addEdge({ id: 'TEMPLATE_E182', u: 'TEMPLATE_67', v: 'TEMPLATE_68', weight: 79 });
  g.addEdge({ id: 'TEMPLATE_E183', u: 'TEMPLATE_66', v: 'TEMPLATE_69', weight: 98 });
  g.addEdge({ id: 'TEMPLATE_E184', u: 'TEMPLATE_66', v: 'TEMPLATE_28', weight: 82 });
  g.addEdge({ id: 'TEMPLATE_E185', u: 'TEMPLATE_69', v: 'TEMPLATE_67', weight: 109 });
  g.addEdge({ id: 'TEMPLATE_E186', u: 'TEMPLATE_68', v: 'TEMPLATE_66', weight: 85 });
  g.addEdge({ id: 'TEMPLATE_E187', u: 'TEMPLATE_68', v: 'TEMPLATE_69', weight: 45 });
  g.addEdge({ id: 'TEMPLATE_E188', u: 'TEMPLATE_68', v: 'TEMPLATE_65', weight: 122 });
  g.addEdge({ id: 'TEMPLATE_E189', u: 'TEMPLATE_74', v: 'TEMPLATE_73', weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E190', u: 'TEMPLATE_73', v: 'TEMPLATE_72', weight: 59 });
  g.addEdge({ id: 'TEMPLATE_E191', u: 'TEMPLATE_68', v: 'TEMPLATE_72', weight: 85 });
  g.addEdge({ id: 'TEMPLATE_E192', u: 'TEMPLATE_72', v: 'TEMPLATE_69', weight: 96 });
  g.addEdge({ id: 'TEMPLATE_E193', u: 'TEMPLATE_69', v: 'TEMPLATE_28', weight: 78 });
  g.addEdge({ id: 'TEMPLATE_E194', u: 'TEMPLATE_69', v: 'TEMPLATE_26', weight: 105 });
  g.addEdge({ id: 'TEMPLATE_E195', u: 'TEMPLATE_26', v: 'TEMPLATE_71', weight: 142 });
  g.addEdge({ id: 'TEMPLATE_E196', u: 'TEMPLATE_25', v: 'TEMPLATE_26', weight: 119 });
  g.addEdge({ id: 'TEMPLATE_E197', u: 'TEMPLATE_22', v: 'TEMPLATE_26', weight: 117 });
  g.addEdge({ id: 'TEMPLATE_E198', u: 'TEMPLATE_22', v: 'TEMPLATE_27', weight: 76 });
  g.addEdge({ id: 'TEMPLATE_E199', u: 'TEMPLATE_29', v: 'TEMPLATE_27', weight: 72 });
  g.addEdge({ id: 'TEMPLATE_E200', u: 'TEMPLATE_29', v: 'TEMPLATE_64', weight: 43 });
  g.addEdge({ id: 'TEMPLATE_E201', u: 'TEMPLATE_27', v: 'TEMPLATE_81', weight: 82 });
  g.addEdge({ id: 'TEMPLATE_E202', u: 'TEMPLATE_27', v: 'TEMPLATE_21', weight: 105 });
  g.addEdge({ id: 'TEMPLATE_E203', u: 'TEMPLATE_27', v: 'TEMPLATE_20', weight: 150 });
  g.addEdge({ id: 'TEMPLATE_E204', u: 'TEMPLATE_21', v: 'TEMPLATE_19', weight: 63 });
  g.addEdge({ id: 'TEMPLATE_E205', u: 'TEMPLATE_21', v: 'TEMPLATE_18', weight: 84 });
  g.addEdge({ id: 'TEMPLATE_E206', u: 'TEMPLATE_21', v: 'TEMPLATE_30', weight: 133 });
  g.addEdge({ id: 'TEMPLATE_E207', u: 'TEMPLATE_22', v: 'TEMPLATE_81', weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E208', u: 'TEMPLATE_72', v: 'TEMPLATE_71', weight: 56 });
  g.addEdge({ id: 'TEMPLATE_E209', u: 'TEMPLATE_70', v: 'TEMPLATE_72', weight: 54 });
  g.addEdge({ id: 'TEMPLATE_E210', u: 'TEMPLATE_73', v: 'TEMPLATE_76', weight: 44 });
  g.addEdge({ id: 'TEMPLATE_E211', u: 'TEMPLATE_76', v: 'TEMPLATE_72', weight: 67 });
  g.addEdge({ id: 'TEMPLATE_E212', u: 'TEMPLATE_76', v: 'TEMPLATE_71', weight: 114 });
  g.addEdge({ id: 'TEMPLATE_E213', u: 'TEMPLATE_31', v: 'TEMPLATE_29', weight: 99 });
  g.addEdge({ id: 'TEMPLATE_E214', u: 'TEMPLATE_29', v: 'TEMPLATE_37', weight: 60 });
  g.addEdge({ id: 'TEMPLATE_E215', u: 'TEMPLATE_32', v: 'TEMPLATE_29', weight: 117 });
  g.addEdge({ id: 'TEMPLATE_E216', u: 'TEMPLATE_32', v: 'TEMPLATE_64', weight: 117 });
  g.addEdge({ id: 'TEMPLATE_E217', u: 'TEMPLATE_64', v: 'TEMPLATE_37', weight: 88 });
  g.addEdge({ id: 'TEMPLATE_E218', u: 'TEMPLATE_29', v: 'TEMPLATE_34', weight: 81 });
  g.addEdge({ id: 'TEMPLATE_E219', u: 'TEMPLATE_34', v: 'TEMPLATE_36', weight: 65 });
  g.addEdge({ id: 'TEMPLATE_E220', u: 'TEMPLATE_34', v: 'TEMPLATE_28', weight: 106 });
  g.addEdge({ id: 'TEMPLATE_E221', u: 'TEMPLATE_28', v: 'TEMPLATE_36', weight: 80 });
  g.addEdge({ id: 'TEMPLATE_E222', u: 'TEMPLATE_73', v: 'TEMPLATE_77', weight: 75 });
  g.addEdge({ id: 'TEMPLATE_E223', u: 'TEMPLATE_67', v: 'TEMPLATE_73', weight: 160 });
  g.addEdge({ id: 'TEMPLATE_E224', u: 'TEMPLATE_73', v: 'TEMPLATE_68', weight: 108 });
  g.addEdge({ id: 'TEMPLATE_E225', u: 'TEMPLATE_68', v: 'TEMPLATE_74', weight: 131 });
  g.addEdge({ id: 'TEMPLATE_E226', u: 'TEMPLATE_72', v: 'TEMPLATE_65', weight: 173 });
  g.addEdge({ id: 'TEMPLATE_E227', u: 'TEMPLATE_60', v: 'TEMPLATE_65', weight: 208 });
  g.addEdge({ id: 'TEMPLATE_E228', u: 'TEMPLATE_19', v: 'TEMPLATE_20', weight: 50 });
  g.addEdge({ id: 'TEMPLATE_E229', u: 'TEMPLATE_18', v: 'TEMPLATE_81', weight: 102 });
  g.addEdge({ id: 'TEMPLATE_E230', u: 'TEMPLATE_8', v: 'TEMPLATE_20', weight: 105 });
  g.addEdge({ id: 'TEMPLATE_E231', u: 'TEMPLATE_11', v: 'TEMPLATE_20', weight: 100 });
  g.addEdge({ id: 'TEMPLATE_E232', u: 'TEMPLATE_12', v: 'TEMPLATE_10', weight: 87 });
  g.addEdge({ id: 'TEMPLATE_E233', u: 'TEMPLATE_9', v: 'TEMPLATE_14', weight: 125 });
  g.addEdge({ id: 'TEMPLATE_E234', u: 'TEMPLATE_29', v: 'TEMPLATE_26', weight: 129 });

  return g;
}
