import { createGraph } from '../models/graph.js';

export const MAP_WIDTH = 1024;
export const MAP_HEIGHT = 512;

export function createCampusGraph() {
  const g = createGraph();
  
  // TEMPLATE VERTICES
  g.addVertex({ id: 'SLOAN',      name: 'SLOAN',      x: 38,    y: 168, isTerminal: false });
  g.addVertex({ id: 'DANA',       name: 'DANA',       x: 55,    y: 341, isTerminal: false });
  g.addVertex({ id: 'CARPENTER',  name: 'CARPENTER',  x: 167,   y: 347, isTerminal: false });
  g.addVertex({ id: 'DAGGY',      name: 'DAGGY',      x: 239,   y: 434, isTerminal: false });
  g.addVertex({ id: 'MLA',        name: 'MLA',        x: 322,   y: 430, isTerminal: false });
  g.addVertex({ id: 'MORRIL',     name: 'MORRIL',     x: 327,   y: 260, isTerminal: false });
  g.addVertex({ id: 'GOERTZEN',   name: 'GOERTZEN',   x: 321,   y: 152, isTerminal: false });
  g.addVertex({ id: 'THOMPSON',   name: 'THOMPSON',   x: 339,   y: 51,  isTerminal: false });
  g.addVertex({ id: 'JACKSON',    name: 'JACKSON',    x: 410,   y: 137, isTerminal: false });
  g.addVertex({ id: 'MURROW',     name: 'MURROW',     x: 466,   y: 179, isTerminal: false });
  g.addVertex({ id: 'BRYAN',      name: 'BRYAN',      x: 543,   y: 21,  isTerminal: false });
  g.addVertex({ id: 'HOLLAND',    name: 'HOLLAND',    x: 690,   y: 54,  isTerminal: false });
  g.addVertex({ id: 'TERRELL',    name: 'TERRELL',    x: 768,   y: 65,  isTerminal: false });
  g.addVertex({ id: 'CUB',        name: 'CUB',        x: 899,   y: 100, isTerminal: false });
  g.addVertex({ id: 'WILSON',     name: 'WILSON',     x: 891,   y: 259, isTerminal: false });
  g.addVertex({ id: 'TODDA',      name: 'TODDA',      x: 766,   y: 271, isTerminal: false });
  g.addVertex({ id: 'TODD',       name: 'TODD',       x: 717,   y: 369, isTerminal: false });
  g.addVertex({ id: 'COLLEGE',    name: 'COLLEGE',    x: 670,   y: 227, isTerminal: false });
  g.addVertex({ id: 'FULMERVF',   name: 'FULMERVF',   x: 655,   y: 427, isTerminal: false });
  g.addVertex({ id: 'FULMERL',    name: 'FULMERL',    x: 653,   y: 483, isTerminal: false });
  g.addVertex({ id: 'FULMERA',    name: 'FULMERA',    x: 734,   y: 490, isTerminal: false });
  g.addVertex({ id: 'FULMERS',    name: 'FULMERS',    x: 801,   y: 492, isTerminal: false });
  g.addVertex({ id: 'TROY',       name: 'TROY',       x: 877,   y: 495, isTerminal: false });
  g.addVertex({ id: 'JOHNSON',    name: 'JOHNSON',    x: 858,   y: 391, isTerminal: false });
  g.addVertex({ id: 'SMITH',      name: 'SMITH',      x: 1004,  y: 371, isTerminal: false });
  g.addVertex({ id: 'SCHNITZER',  name: 'SCHNITZER',  x: 1010,  y: 248, isTerminal: false });
  g.addVertex({ id: 'ABELSON',    name: 'ABELSON',    x: 519,   y: 433, isTerminal: false });
  g.addVertex({ id: 'HEALD',      name: 'HEALD',      x: 420,   y: 452, isTerminal: false });
  g.addVertex({ id: 'EASTLICK',   name: 'EASTLICK',   x: 430,   y: 360, isTerminal: false });
  g.addVertex({ id: 'EME',        name: 'EME',        x: 16,    y: 213, isTerminal: false });

  // TEMPLATE EDGES
  g.addEdge({ id: 'TEMPLATE_E01', u: 'SLOAN',     v: 'EME',       weight: 50 });
  g.addEdge({ id: 'TEMPLATE_E02', u: 'DANA',      v: 'SLOAN',     weight: 174 });
  g.addEdge({ id: 'TEMPLATE_E03', u: 'DANA',      v: 'EME',       weight: 134 });
  g.addEdge({ id: 'TEMPLATE_E04', u: 'DANA',      v: 'CARPENTER', weight: 112 });
  g.addEdge({ id: 'TEMPLATE_E05', u: 'SLOAN',     v: 'CARPENTER', weight: 221 });
  g.addEdge({ id: 'TEMPLATE_E06', u: 'DAGGY',     v: 'CARPENTER', weight: 113 });
  g.addEdge({ id: 'TEMPLATE_E07', u: 'DAGGY',     v: 'MLA',       weight: 83 });
  g.addEdge({ id: 'TEMPLATE_E08', u: 'CARPENTER', v: 'MORRIL',    weight: 182 });
  g.addEdge({ id: 'TEMPLATE_E09', u: 'DAGGY',     v: 'MORRIL',    weight: 195 });
  g.addEdge({ id: 'TEMPLATE_E10', u: 'MLA',       v: 'MORRIL',    weight: 170 });
  g.addEdge({ id: 'TEMPLATE_E11', u: 'GOERTZEN',  v: 'CARPENTER', weight: 248 });
  g.addEdge({ id: 'TEMPLATE_E12', u: 'GOERTZEN',  v: 'SLOAN',     weight: 283 });
  g.addEdge({ id: 'TEMPLATE_E13', u: 'GOERTZEN',  v: 'MORRIL',    weight: 108 });
  g.addEdge({ id: 'TEMPLATE_E14', u: 'GOERTZEN',  v: 'THOMPSON',  weight: 103 });
  g.addEdge({ id: 'TEMPLATE_E15', u: 'JACKSON',   v: 'THOMPSON',  weight: 112 });
  g.addEdge({ id: 'TEMPLATE_E16', u: 'GOERTZEN',  v: 'JACKSON',   weight: 90 });
  g.addEdge({ id: 'TEMPLATE_E17', u: 'MORRIL',    v: 'JACKSON',   weight: 148 });
  g.addEdge({ id: 'TEMPLATE_E18', u: 'MORRIL',    v: 'EASTLICK',  weight: 144 });
  g.addEdge({ id: 'TEMPLATE_E19', u: 'JACKSON',   v: 'MURROW',    weight: 70 });
  g.addEdge({ id: 'TEMPLATE_E20', u: 'MLA',       v: 'HEALD',     weight: 100 });
  g.addEdge({ id: 'TEMPLATE_E21', u: 'MLA',       v: 'EASTLICK',  weight: 129 });
  g.addEdge({ id: 'TEMPLATE_E22', u: 'EASTLICK',  v: 'MURROW',    weight: 185 });
  g.addEdge({ id: 'TEMPLATE_E23', u: 'MURROW',    v: 'BRYAN',     weight: 176 });
  g.addEdge({ id: 'TEMPLATE_E24', u: 'BRYAN',     v: 'JACKSON',   weight: 176 });
  g.addEdge({ id: 'TEMPLATE_E25', u: 'BRYAN',     v: 'THOMPSON',  weight: 206 });
  g.addEdge({ id: 'TEMPLATE_E26', u: 'MURROW',    v: 'COLLEGE',   weight: 210 });
  g.addEdge({ id: 'TEMPLATE_E27', u: 'BRYAN',     v: 'HOLLAND',   weight: 151 });
  g.addEdge({ id: 'TEMPLATE_E28', u: 'COLLEGE',   v: 'HOLLAND',   weight: 174 });
  g.addEdge({ id: 'TEMPLATE_E29', u: 'COLLEGE',   v: 'BRYAN',     weight: 242 });
  g.addEdge({ id: 'TEMPLATE_E30', u: 'HOLLAND',   v: 'MURROW',    weight: 257 });
  g.addEdge({ id: 'TEMPLATE_E31', u: 'HOLLAND',   v: 'TERRELL',   weight: 79 });
  g.addEdge({ id: 'TEMPLATE_E32', u: 'TERRELL',   v: 'CUB',       weight: 136 });
  g.addEdge({ id: 'TEMPLATE_E33', u: 'CUB',       v: 'SCHNITZER', weight: 185 });
  g.addEdge({ id: 'TEMPLATE_E34', u: 'SCHNITZER', v: 'SMITH',     weight: 123 });
  g.addEdge({ id: 'TEMPLATE_E35', u: 'SMITH',     v: 'TROY',      weight: 177 });
  g.addEdge({ id: 'TEMPLATE_E36', u: 'TROY',      v: 'FULMERS',   weight: 76 });
  g.addEdge({ id: 'TEMPLATE_E37', u: 'FULMERS',   v: 'FULMERA',   weight: 67 });
  g.addEdge({ id: 'TEMPLATE_E38', u: 'FULMERA',   v: 'FULMERL',   weight: 81 });
  g.addEdge({ id: 'TEMPLATE_E39', u: 'FULMERL',   v: 'FULMERVF',  weight: 56 });
  g.addEdge({ id: 'TEMPLATE_E40', u: 'FULMERL',   v: 'ABELSON',   weight: 143 });
  g.addEdge({ id: 'TEMPLATE_E41', u: 'FULMERVF',  v: 'ABELSON',   weight: 136 });
  g.addEdge({ id: 'TEMPLATE_E42', u: 'ABELSON',   v: 'HEALD',     weight: 101 });
  g.addEdge({ id: 'TEMPLATE_E43', u: 'ABELSON',   v: 'EASTLICK',  weight: 115 });
  g.addEdge({ id: 'TEMPLATE_E44', u: 'HEALD',     v: 'EASTLICK',  weight: 93 });
  g.addEdge({ id: 'TEMPLATE_E45', u: 'TODD',      v: 'TODDA',     weight: 110 });
  g.addEdge({ id: 'TEMPLATE_E46', u: 'TODDA',     v: 'WILSON',    weight: 126 });
  g.addEdge({ id: 'TEMPLATE_E47', u: 'TODDA',     v: 'COLLEGE',   weight: 106 });
  g.addEdge({ id: 'TEMPLATE_E48', u: 'JOHNSON',   v: 'WILSON',    weight: 136 });
  g.addEdge({ id: 'TEMPLATE_E49', u: 'JOHNSON',   v: 'TODD',      weight: 143 });
  g.addEdge({ id: 'TEMPLATE_E50', u: 'TROY',      v: 'JOHNSON',   weight: 106 });
  g.addEdge({ id: 'TEMPLATE_E51', u: 'SMITH',     v: 'JOHNSON',   weight: 147 });
  g.addEdge({ id: 'TEMPLATE_E52', u: 'WILSON',    v: 'SCHNITZER', weight: 120 });
  g.addEdge({ id: 'TEMPLATE_E53', u: 'WILSON',    v: 'CUB',       weight: 159 });
  g.addEdge({ id: 'TEMPLATE_E54', u: 'SMITH',     v: 'WILSON',    weight: 159 });
  g.addEdge({ id: 'TEMPLATE_E55', u: 'JOHNSON',   v: 'SCHNITZER', weight: 209 });
  g.addEdge({ id: 'TEMPLATE_E56', u: 'JOHNSON',   v: 'FULMERS',   weight: 116 });
  g.addEdge({ id: 'TEMPLATE_E57', u: 'FULMERA',   v: 'TODD',      weight: 122 });
  g.addEdge({ id: 'TEMPLATE_E58', u: 'FULMERVF',  v: 'TODD',      weight: 85 });
  g.addEdge({ id: 'TEMPLATE_E59', u: 'ABELSON',   v: 'COLLEGE',   weight: 255 });
  g.addEdge({ id: 'TEMPLATE_E60', u: 'MURROW',    v: 'FULMERVF',  weight: 312 });
  g.addEdge({ id: 'TEMPLATE_E61', u: 'MURROW',    v: 'TODD',      weight: 315 });
  g.addEdge({ id: 'TEMPLATE_E62', u: 'EASTLICK',  v: 'COLLEGE',   weight: 274 });
  g.addEdge({ id: 'TEMPLATE_E63', u: 'TERRELL',   v: 'TODDA',     weight: 206 });
  g.addEdge({ id: 'TEMPLATE_E64', u: 'WILSON',    v: 'TERRELL',   weight: 230 });
  g.addEdge({ id: 'TEMPLATE_E65', u: 'HOLLAND',   v: 'TODDA',     weight: 230 });
  g.addEdge({ id: 'TEMPLATE_E66', u: 'CUB',       v: 'TODDA',     weight: 217 });
  g.addEdge({ id: 'TEMPLATE_E67', u: 'TERRELL',   v: 'COLLEGE',   weight: 189 });
  g.addEdge({ id: 'TEMPLATE_E68', u: 'THOMPSON',  v: 'SLOAN',     weight: 323 });
  g.addEdge({ id: 'TEMPLATE_E69', u: 'CUB',       v: 'COLLEGE',   weight: 262 });
  g.addEdge({ id: 'TEMPLATE_E70', u: 'HOLLAND',   v: 'WILSON',    weight: 287 });
  g.addEdge({ id: 'TEMPLATE_E71', u: 'BRYAN',     v: 'ABELSON',   weight: 413 });
  g.addEdge({ id: 'TEMPLATE_E72', u: 'BRYAN',     v: 'FULMERVF',  weight: 421 });
  g.addEdge({ id: 'TEMPLATE_E73', u: 'EASTLICK',  v: 'TODDA',     weight: 348 });
  g.addEdge({ id: 'TEMPLATE_E74', u: 'FULMERVF',  v: 'GOERTZEN',  weight: 433 });
  g.addEdge({ id: 'TEMPLATE_E75', u: 'JACKSON',   v: 'MLA',       weight: 306 });

  return g;
}
